language: rust
rust:
  - stable
  - 1.36.0
  - beta
  - nightly

env:
  - ARCH=x86_64 RUSTFLAGS='-C target-feature=+aes -C target-cpu=native'
  - ARCH=i686 RUSTFLAGS='-C target-feature=+aes -C target-cpu=native'

addons:
  apt:
    packages:
      - gcc-multilib

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
